databases:
  - name: badjivon
    databaseName: badjivon
    user: badjivon

services:
  - type: web
    name: badjivon
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: badjivon
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
